version: '3.7'
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/Users/ye/Documents/work/itgenio/python/internship_crm/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    environment:
      - POSTGRES_USER=internship_crm
      - POSTGRES_PASSWORD=internship_crm
      - POSTGRES_DB=internship_crm_dev
volumes:
  postgres_data: