version: '3.7'
services:
  web:
    build: .
    volumes:
      - .:/Users/ye/Documents/work/itgenio/python/internship_crm/
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
      - redis
  celery:
    build: .
    command: celery worker -app=core --loglevel=info
    volumes:
      - .:/Users/ye/Documents/work/itgenio/python/internship_crm/
    depends_on:
      - web
      - redis
  db:
    image: postgres:12.0-alpine
    env_file:
      - .env
    volumes:
      - ./pg_data:/var/lib/postgresql/data
  redis:
    image: 'redis:alpine'
