version: '3.7'
services:
  web:
    build: .
    volumes:
      - .:/Users/ye/Documents/work/itgenio/python/internship_crm/
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db

  celery:
    build: .
    command: celery -A internship_crm worker -l INFO
    volumes:
      - .:/Users/ye/Documents/work/itgenio/python/internship_crm/
    env_file:
      - .env
    depends_on:
      - celery-beat
      - flower
      - redis
  celery-beat:
    build: .
    command: celery -A internship_crm beat -l INFO
    volumes:
      - .:/Users/ye/Documents/work/itgenio/python/internship_crm/
    env_file:
      - .env
  db:
    image: postgres:12.0-alpine
    env_file:
      - .env
    volumes:
      - ./pg_data:/var/lib/postgresql/data
  redis:
    image: redis:alpine
  flower:
    image: mher/flower
    env_file:
      - .env
    ports:
      - 8888:8888