# Generated by Django 3.2.7 on 2021-09-06 16:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car_showroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('establishment', models.DateField(auto_created=True)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProviderSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('starts', models.DateField(blank=True)),
                ('duration_days', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(limit_value=5)])),
                ('discount', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(limit_value=5), django.core.validators.MaxValueValidator(limit_value=60)])),
                ('cars_list', models.ManyToManyField(to='provider.Car')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.provider')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProviderCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=0)])),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.car')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.provider')),
            ],
        ),
        migrations.AddField(
            model_name='provider',
            name='car_list',
            field=models.ManyToManyField(through='provider.ProviderCar', to='provider.Car'),
        ),
        migrations.AddField(
            model_name='provider',
            name='car_showroom_list',
            field=models.ManyToManyField(to='car_showroom.CarShowroom'),
        ),
    ]
