# Generated by Django 3.2.7 on 2021-09-06 16:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarShowroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('location', django_countries.fields.CountryField(max_length=2)),
                ('specs', models.JSONField()),
                ('balance', models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=0)])),
                ('unique_customers', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='CarShowroomCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CarShowroomCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bought', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CarShowroomSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('starts', models.DateField(blank=True)),
                ('duration_days', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(limit_value=5)])),
                ('discount', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(limit_value=5), django.core.validators.MaxValueValidator(limit_value=60)])),
                ('car_showroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_showroom.carshowroom')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
